*** Variables ***
${MSG_SUCCESS_REGISTER}              Cadastro realizado com sucesso!
${MSG_ERROR_NAME_SURNAME_REQUIRED}   Preencha com nome e sobrenome.
${MSG_ERROR_NAME_REQUIRED}           O campo de nome é obrigatório.
${MSG_ERROR_EMAIL_REQUIRED}          O campo de e-mail é obrigatório.
${MSG_ERROR_EMAIL_INVALID}           Por favor, insira um e-mail válido.
${MSG_ERROR_PASSWORD_RULES}          A senha deve conter entre 8 e 12 caracteres, incluindo ao menos uma letra maiúscula, um número e um caractere especial.
${MSG_ERROR_PASSWORD_MISMATCH}       As senhas não coincidem.
${MSG_ERROR_CONFIRM_PASSWORD}        Confirme sua senha.
${MSG_ERROR_PROFILE_REQUIRED}        Por favor, selecione o perfil.
${MSG_ERROR_GENERIC_REGISTER}        Erro ao realizar cadastro. Tente novamente.